### ISSUE TITLE
OpenStreetMap in Gmap returns nothing

### ISSUE THREAD

**Issue by PerMJ** [judero01col/GMap.NET#120] opened 2021-02-06 12:29 UTC
Suddenly the program part below no longer works. The variable "Route" becomes nothing.
Are you familiar with problems with OpenStreetMap?

Dim Route = GMapProviders.OpenStreetMap.GetRoute(point1, point2, False, False, 0)

**Comment by KeanoNeumann** [comment] 2021-02-06 19:08
Same here.

**Comment by pahahi** [comment] 2021-02-07 11:13
Hello.

That's right. GetRoute function is not  working.

**Comment by jxburns** [comment] 2021-02-13 19:07
Confirm same problem on all my systems using GetRoute. Showing a map works OK. Does anyone know if the developer is actively trying to fix this? Thanks

**Comment by zgabi** [comment] 2021-02-13 19:40
I guess no... If you create a PR, I'll check it, and megre it.

**Comment by jxburns** [comment] 2021-02-13 20:09
I don't know how to fix it. I thoughr PRs were meant to suggest a fix unless I misunderstood. I never have used GitHub to report a problem before.

**Comment by fvilanova** [comment] 2021-02-15 07:50
Same problem with getroute, any suggestion?

**Comment by zgabi** [comment] 2021-02-15 13:56
Whar .NET version do you use? If not .NET 5, please try it.. it seems that OSM does not work with .NET 4.x, it shows SSL errors. (for the tile download, I haven't tried to routes)

**Comment by jxburns** [comment] 2021-02-15 14:41
I use .NET 4.8 and the map tiles download fine with map displaying OK. It is just the routes that do not work.

**Comment by zgabi** [comment] 2021-02-15 17:52
Found the reason. OSM provider is using yournavigarion.org for the routes:
 https://github.com/judero01col/GMap.NET/blob/6b42103a4b462028cd6d1d6c1d54dc63fd088114/GMap.NET/GMap.NET.Core/MapProviders/OpenStreetMap/OpenStreetMapProvider.cs#L201-L202
 
 YourNavigation.org is down.. so the 3d party provider problem, cannot be fixed in this library.
Duplicate of #118

**Comment by jxburns** [comment] 2021-02-15 18:07
Thanks for finding that. Hopefully only a minor problem as the domain seems active - just the website is down. If not hope there is an alternative that can be used in GMAP.

**Comment by PerMJ** [comment] 2021-02-15 21:06
I think we need to find another map provider:
[https://forum.openstreetmap.org/viewtopic.php?id=735&p=11](url) #253

**Comment by judero01col** [comment] 2021-03-18 15:24
I have found the OpenStreetMap map provider, when I have a space I will make the change in the current provider of the library.

Greetings. 

https://routing.openstreetmap.de/routed-car/route/v1/driving/-69.92,9.388;-70.70800781250001,8.90678000752024?overview=false&geometries=polyline&steps=true

https://routing.openstreetmap.de/routed-foot/route/v1/driving/-69.92,9.388;-70.70800781250001,8.90678000752024?overview=false&geometries=polyline&steps=true

https://routing.openstreetmap.de/routed-bike/route/v1/driving/-69.92,9.388;-70.70800781250001,8.90678000752024?overview=false&geometries=polyline&steps=true

**Comment by fvilanova** [comment] 2021-03-24 06:55
Perfect!!! 
Thanks

**Comment by jxburns** [comment] 2021-10-16 19:01
Has there been any update/solution to this for .NET 4.8?

**Comment by jxburns** [comment] 2021-11-24 13:23
Saw an update to v 2.0.3 but this problem still exists.

**Comment by judero01col** [comment] 2022-06-02 20:04
please test if version 2.1.6 fixes your problem.

**Comment by jxburns** [comment] 2022-06-05 01:46
This now works perfectly with 2.1.6. Thanks for fixing this.

**Closed** 2022-06-23 14:28 UTC
